### ISSUE TITLE
Does not work under Wine

### ISSUE THREAD

**Issue by quisys** [acidicoala/dream-api#15]
When running under a wineprefix, the error `(317, 'FormatMessageW', 'Message 0x%1 not found in file %2.')` is thrown out, and the program does not open.

**Comment by acidicoala** [comment]
Closing this since it is not an issue. DreamAPI was never advertised to support Wine.

If someone is willing to adapt the source to it, they are free to submit a Pull Request, but I myself don't have the means to develop and test this on Wine or any other Windows emulation layer.
