### ISSUE TITLE
Stuck at Fetching Origin Entitlements

### ISSUE THREAD

**Issue by g-yui** [acidicoala/dream-api#4]
I messed up a line while working on the fork and it crashed, after crashing it got stuck at fetching origin entitlements, plz help (o;TωT)o

**Comment by g-yui** [comment]
After further testing it has become apparent that the program configured a proxy on my pc, which either didn't notice was there or it got misaligned during the crash, that was the reason behind the inability to fetch origin entitlements later on, the proxy is great while the software works as intended, but if for any reason whatsoever it crashes/is forcefully closed, it will block every request later on, I use a hardened version of Firefox, that's why I could bypass the proxy, but you should consider making an script to deactivate the proxy, end users may not have the know-how to deactivate it themselves, or add a check to see if any of the tasks are taking too long, so you can just prompt the user with a reset button instead of making the app do an infinite loop.

Man, gotta love those infinite loop bugs, seem to happen to both of us as of late 😆

**Comment by acidicoala** [comment]
In the forum topic, I have written this in the usage instructions:
>**Note**: When you run DreamAPI, it automatically configures your system to use DreamAPI as its proxy server. And when you shutdown DreamAPI, it disables the proxy server usage. This means that if the DreamAPI has ended unexpectedly (for instance it crashed or you have killed its process from the task manager) then you would need to manually disable the usage of proxy server in the system settings in order to restore connectivity. Or you can simply run DreamAPI again and properly shut it down.

**Comment by g-yui** [comment]
As it has been previously made apparent, I don't read what I should 🤣

**Comment by acidicoala** [comment]
Alright, let me know if there is anything else unclear or could be improved

**Comment by g-yui** [comment]
The check I suggested sounds like a good idea, some other goof may stumble upon a random crash at some point and get all their connections blocked by the proxy.

**Comment by acidicoala** [comment]
Released a new version which adds some error handling logic to the fetching: https://github.com/acidicoala/dream-api/releases/tag/v1.1.2
